#!/bin/bash

# Local Development Script with Cloud SQL
# This script starts Cloud SQL Proxy for local development against production database

set -e

# Configuration variables
PROJECT_ID="${GCP_PROJECT_ID:-your-project-id}"
CLOUD_SQL_INSTANCE="${CLOUD_SQL_INSTANCE:-adulting-db}"
REGION="${GCP_REGION:-us-central1}"
LOCAL_PORT="${LOCAL_PORT:-5432}"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Cloud SQL Proxy - Local Development${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""

# Check if cloud_sql_proxy is installed
if ! command -v cloud_sql_proxy &> /dev/null; then
    echo -e "${YELLOW}Cloud SQL Proxy not found. Installing...${NC}"

    # Detect OS
    OS=$(uname -s)
    case "$OS" in
        Darwin)
            curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.darwin.amd64
            ;;
        Linux)
            curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
            ;;
        *)
            echo -e "${RED}Unsupported OS: $OS${NC}"
            exit 1
            ;;
    esac

    chmod +x cloud_sql_proxy
    sudo mv cloud_sql_proxy /usr/local/bin/
    echo -e "${GREEN}Cloud SQL Proxy installed!${NC}"
fi

# Get connection name
echo -e "${YELLOW}Retrieving Cloud SQL connection name...${NC}"
CONNECTION_NAME=$(gcloud sql instances describe "${CLOUD_SQL_INSTANCE}" \
    --format="value(connectionName)" \
    --project="${PROJECT_ID}")

echo -e "${GREEN}Connection name: ${CONNECTION_NAME}${NC}"
echo ""

# Get DATABASE_URL from Secret Manager
echo -e "${YELLOW}Retrieving DATABASE_URL from Secret Manager...${NC}"
DATABASE_URL=$(gcloud secrets versions access latest \
    --secret="database-url" \
    --project="${PROJECT_ID}")

# Update .env.local
echo -e "${YELLOW}Creating .env.local file...${NC}"
cat > .env.local <<EOF
# Auto-generated by dev-cloud-sql.sh
# This file is gitignored and safe for local development

DATABASE_URL="${DATABASE_URL}"
NODE_ENV="development"
EOF

echo -e "${GREEN}.env.local created!${NC}"
echo ""

# Start Cloud SQL Proxy
echo -e "${YELLOW}Starting Cloud SQL Proxy on port ${LOCAL_PORT}...${NC}"
echo -e "${YELLOW}Press Ctrl+C to stop${NC}"
echo ""

cloud_sql_proxy -instances="${CONNECTION_NAME}"=tcp:${LOCAL_PORT}
